// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "54d6d557-a96c-4e45-92ef-92953d14ec14");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1536827183);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1536827303);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1536750007);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1536827063);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1536750265);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.lastDir", "/home/usuario");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1536749978);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 69);
user_pref("browser.newtabpage.activity-stream.impressionId", "{72f17f28-c997-426e-bc27-8a106f49e942}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1536789600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1536749981);
user_pref("browser.onboarding.notification.prompt-count", 1);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser,onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1536827038850");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1536828813850");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1536827039509");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1536830639509");
user_pref("browser.search.countryCode", "ES");
user_pref("browser.search.region", "ES");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20180905220717");
user_pref("browser.shell.checkDefaultBrowser", true);
user_pref("browser.slowStartup.averageTime", 5166);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage", "https://bib.us.es/");
user_pref("browser.startup.homepage_override.buildID", "20180905220717");
user_pref("browser.startup.homepage_override.mstone", "62.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 1);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1536749986979");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "62.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "af68f800e1134ca0abf4e48888027217");
user_pref("extensions.blocklist.lastModified", "Mon, 10 Sep 2018 21:03:37 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1536827184);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20180905220717");
user_pref("extensions.lastAppVersion", "62.0");
user_pref("extensions.lastPlatformVersion", "62.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{b504dc50-e486-4fcc-861f-8ee6e5a6339b}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.2\"}}}");
user_pref("extensions.webextensions.uuids", "{\"webcompat@mozilla.org\":\"f41ec402-ec01-4963-8700-af751d610a51\",\"screenshots@mozilla.org\":\"37462104-8793-49f5-afc6-028f789782aa\",\"fxmonitor@mozilla.org\":\"f8573b2c-ae87-46ce-b0d3-d590a7da21f4\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1536827089);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20180905220717");
user_pref("media.gmp-manager.lastCheck", 1536827088);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("pref.browser.homepage.disable_button.restore_default", false);
user_pref("pref.general.disable_button.default_browser", false);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "b9a5e13a-cb1d-40b3-b538-edaf88fd7bfd");
user_pref("services.blocklist.addons.checked", 1536775300);
user_pref("services.blocklist.gfx.checked", 1536775300);
user_pref("services.blocklist.onecrl.checked", 1536775300);
user_pref("services.blocklist.pinning.checked", 1536775300);
user_pref("services.blocklist.plugins.checked", 1536775300);
user_pref("services.settings.clock_skew_seconds", 52003);
user_pref("services.settings.last_etag", "\"1536774723903\"");
user_pref("services.settings.last_update_seconds", 1536775300);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1536827030);
user_pref("toolkit.telemetry.cachedClientID", "c37b271a-8e4e-4ce2-b53c-e0fd38795dee");
user_pref("toolkit.telemetry.previousBuildID", "20180905220717");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
